### ISSUE TITLE
Did not give me a girlfriend

### ISSUE THREAD

**Issue by Benjozork** [hamza1311/BitchBot#7]
**Expected behaviour**

- Gave me a girlfriend

**Actual behaviour**

- Didn't

**Comment by Benjozork** [comment]
Maintainer is rude

Use <other OSS project> instead

**Comment by hamza1311** [comment]
I'd appreciate if you PRed a fix for this

**Comment by crrapi** [comment]
Can repro as of commit 76636d00c3badc8b4f3c4cb7144fab26ee0504b2
